# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.find_or_create_by(:title => "Bed")
@cat1a = Category.find_by_title('Bed')
SubCategory.find_or_create_by(:name => "Bed sheets", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Bed in a bag", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Bed covers", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Comforters", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Duvet covers", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Diwan sets", :category_id => @cat1a.id)
SubCategory.find_or_create_by(:name => "Pillow and inserts", :category_id => @cat1a.id)

Category.find_or_create_by(:title => "Curtains")
@cat2 = Category.find_by_title('Curtains') 
SubCategory.find_or_create_by(:name => "Window curtains", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Door curtains", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Long door curtains", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Curtain accessories", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Sheer curtains", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Tie backs", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Curtain rods", :category_id => @cat2.id)
SubCategory.find_or_create_by(:name => "Blinds", :category_id => @cat2.id)

Category.find_or_create_by(:title => "Furniture")
@cat3 = Category.find_by_title('Furniture') 
SubCategory.find_or_create_by(:name => "Living room", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Dining room", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Bedroom", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Bar and study", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Outdoor", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Luxury", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Doors", :category_id => @cat3.id)
SubCategory.find_or_create_by(:name => "Shoe racks", :category_id => @cat3.id)

Category.find_or_create_by(:title => "Cushions")
@cat4 = Category.find_by_title('Cushions') 
SubCategory.find_or_create_by(:name => "Cushion covers ", :category_id => @cat4.id)
SubCategory.find_or_create_by(:name => "Cushion inserts", :category_id => @cat4.id)
SubCategory.find_or_create_by(:name => "Filled cushions", :category_id => @cat4.id)
SubCategory.find_or_create_by(:name => "Throw", :category_id => @cat3.id)

Category.find_or_create_by(:title => "Decor")
@cat5 = Category.find_by_title('Decor') 
SubCategory.find_or_create_by(:name => "Candles and fragrances", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Candlesticks and Lamps", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Vases and flowers", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Wall decor", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Rugs and carpets", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Home accents", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Handicraft", :category_id => @cat5.id)
SubCategory.find_or_create_by(:name => "Photo frames and albums", :category_id => @cat5.id)

Category.find_or_create_by(:title => "Kids")
@cat6 = Category.find_by_title('Kids') 
SubCategory.find_or_create_by(:name => "Educational", :category_id => @cat6.id)
SubCategory.find_or_create_by(:name => "Party", :category_id => @cat6.id)
SubCategory.find_or_create_by(:name => "Bedroom", :category_id => @cat6.id)
SubCategory.find_or_create_by(:name => "Playroom", :category_id => @cat6.id)
SubCategory.find_or_create_by(:name => "Soft toys and cushions", :category_id => @cat6.id)
SubCategory.find_or_create_by(:name => "Toys", :category_id => @cat6.id)


